CREATE TABLE payment_sessions (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  session_token VARCHAR(64) UNIQUE NOT NULL,
  user_id BIGINT NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at DATETIME NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id)
);
